<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="JAMUNA-NAGARAJ" failures="1" tests="4" name="LoginTest.Login" time="26.144" errors="0" timestamp="2025-03-29T20:50:01 IST" skipped="3">
  <testcase classname="LoginTest.Login" name="loginTest" time="6.082">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="LoginTest.Login" name="loginTest" time="6.600">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="LoginTest.Login" name="loginTest" time="7.581">
    <failure message="Validation is failed expected [http://49.249.28.218:8098/dashbod] but found [http://49.249.28.218:8098/dashboard]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Validation is failed expected [http://49.249.28.218:8098/dashbod] but found [http://49.249.28.218:8098/dashboard]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at LoginTest.Login.loginTest(Login.java:91)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="LoginTest.Login" name="loginTest" time="5.881">
    <skipped/>
  </testcase> <!-- loginTest -->
  <system-out>
    <![CDATA[ContactJamess_1537 added Successfully
CampaignGoGreen_691 added Successfully
CampaignGoGreen_68 added Successfully
CampaignGoGreen_1751 added Successfully]]>
  </system-out>
</testsuite> <!-- LoginTest.Login -->
